from enum import Enum
from pydantic import BaseModel

__all__ = (
    'AccountType',
    'AccountStatus',
    'AccessLevel',
    'SecurityTradingStatus'
)

"""
переделать enums
"""

class AccountType(Enum):
    ACCOUNT_TYPE_UNSPECIFIED = 'ACCOUNT_TYPE_UNSPECIFIED'
    ACCOUNT_TYPE_TINKOFF = 'ACCOUNT_TYPE_TINKOFF'
    ACCOUNT_TYPE_TINKOFF_IIS = 'ACCOUNT_TYPE_TINKOFF_IIS'
    ACCOUNT_TYPE_INVEST_BOX = 'ACCOUNT_TYPE_INVEST_BOX'


class AccountStatus(str, Enum):
    ACCOUNT_STATUS_UNSPECIFIED = 0
    ACCOUNT_STATUS_NEW = 1
    ACCOUNT_STATUS_OPEN = 2
    ACCOUNT_STATUS_CLOSED = 3


class AccessLevel(str, Enum):
    ACCOUNT_ACCESS_LEVEL_UNSPECIFIED = 0
    ACCOUNT_ACCESS_LEVEL_FULL_ACCESS = 1
    ACCOUNT_ACCESS_LEVEL_READ_ONLY = 2
    ACCOUNT_ACCESS_LEVEL_NO_ACCESS = 3


class SecurityTradingStatus(str, Enum):
    SECURITY_TRADING_STATUS_UNSPECIFIED = 0
    SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING = 1
    SECURITY_TRADING_STATUS_OPENING_PERIOD = 2
    SECURITY_TRADING_STATUS_CLOSING_PERIOD = 3
    SECURITY_TRADING_STATUS_BREAK_IN_TRADING = 4
    SECURITY_TRADING_STATUS_NORMAL_TRADING = 5
    SECURITY_TRADING_STATUS_CLOSING_AUCTION = 6
    SECURITY_TRADING_STATUS_DARK_POOL_AUCTION = 7
    SECURITY_TRADING_STATUS_DISCRETE_AUCTION = 8
    SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD = 9
    SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE = 10
    SECURITY_TRADING_STATUS_SESSION_ASSIGNED = 11
    SECURITY_TRADING_STATUS_SESSION_CLOSE = 12
    SECURITY_TRADING_STATUS_SESSION_OPEN = 13
    SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING = 14
    SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING = 15
    SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING = 16


class CouponType(str, Enum):
    COUPON_TYPE_UNSPECIFIED = 0
    COUPON_TYPE_CONSTANT = 1   
    COUPON_TYPE_FLOATING = 2   
    COUPON_TYPE_DISCOUNT = 3  
    COUPON_TYPE_MORTGAGE = 4   
    COUPON_TYPE_FIX = 5
    COUPON_TYPE_VARIABLE = 6   
    COUPON_TYPE_OTHER = 7


class InstrumentIdType(str, Enum):
    INSTRUMENT_ID_UNSPECIFIED = 0
    INSTRUMENT_ID_TYPE_FIGI = 1
    INSTRUMENT_ID_TYPE_TICKER = 2
    INSTRUMENT_ID_TYPE_UID = 3


class InstrumentStatus(str, Enum):
    INSTRUMENT_STATUS_UNSPECIFIED = 0
    INSTRUMENT_STATUS_BASE = 1
    INSTRUMENT_STATUS_ALL = 2


class ShareType(str, Enum):
    SHARE_TYPE_UNSPECIFIED = 0
    SHARE_TYPE_COMMON = 1
    SHARE_TYPE_PREFERRED = 2
    SHARE_TYPE_ADR = 3
    SHARE_TYPE_GDR = 4
    SHARE_TYPE_MLP = 5
    SHARE_TYPE_NY_REG_SHRS = 6
    SHARE_TYPE_CLOSED_END_FUND = 7	
    SHARE_TYPE_REIT = 8


class AssetType(str, Enum):
    ASSET_TYPE_UNSPECIFIED = 0
    ASSET_TYPE_CURRENCY = 1
    ASSET_TYPE_COMMODITY = 2
    ASSET_TYPE_INDEX = 3
    ASSET_TYPE_SECURITY = 4


class StructuredProductType(str, Enum):
    SP_TYPE_UNSPECIFIED = 0
    SP_TYPE_DELIVERABLE = 1
    SP_TYPE_NON_DELIVERABLE = 2


class EditFavoritesActionType(str, Enum):
    EDIT_FAVORITES_ACTION_TYPE_UNSPECIFIED = 0
    EDIT_FAVORITES_ACTION_TYPE_ADD = 1
    EDIT_FAVORITES_ACTION_TYPE_DEL = 2


class RealExchange(str, Enum):
    REAL_EXCHANGE_UNSPECIFIED = 0
    REAL_EXCHANGE_MOEX = 1
    REAL_EXCHANGE_RTS = 2
    REAL_EXCHANGE_OTC = 3


class OrderDirection(str, Enum):
    ORDER_DIRECTION_UNSPECIFIED = 0
    ORDER_DIRECTION_BUY = 1
    ORDER_DIRECTION_SELL = 2


class OrderType(str, Enum):
    ORDER_TYPE_UNSPECIFIED = 0
    ORDER_TYPE_LIMIT = 1
    ORDER_TYPE_MARKET = 2


class OrderExecutionReportStatus(str, Enum):
    EXECUTION_REPORT_STATUS_UNSPECIFIED = 0   
    EXECUTION_REPORT_STATUS_FILL = 1   
    EXECUTION_REPORT_STATUS_REJECTED = 2   
    EXECUTION_REPORT_STATUS_CANCELLED = 3    
    EXECUTION_REPORT_STATUS_NEW = 4   
    EXECUTION_REPORT_STATUS_PARTIALLYFILL = 5    

class OperationState(str, Enum):
    OPERATION_STATE_UNSPECIFIED = 0
    OPERATION_STATE_EXECUTED = 1
    OPERATION_STATE_CANCELED = 2


class OperationType(str, Enum):
    OPERATION_TYPE_UNSPECIFIED = 0   
    OPERATION_TYPE_INPUT = 1   
    OPERATION_TYPE_BOND_TAX = 2   
    OPERATION_TYPE_OUTPUT_SECURITIES = 3 
    OPERATION_TYPE_OVERNIGHT = 4  
    OPERATION_TYPE_TAX = 5    
    OPERATION_TYPE_BOND_REPAYMENT_FULL = 6     
    OPERATION_TYPE_SELL_CARD = 7  
    OPERATION_TYPE_DIVIDEND_TAX = 8   
    OPERATION_TYPE_OUTPUT = 9   
    OPERATION_TYPE_BOND_REPAYMENT = 10  
    OPERATION_TYPE_TAX_CORRECTION = 11 
    OPERATION_TYPE_SERVICE_FEE = 12  
    OPERATION_TYPE_BENEFIT_TAX = 13  
    OPERATION_TYPE_MARGIN_FEE = 14  
    OPERATION_TYPE_BUY = 15  
    OPERATION_TYPE_BUY_CARD = 16  
    OPERATION_TYPE_INPUT_SECURITIES = 17 
    OPERATION_TYPE_BUY_MARGINOPERATION_TYPE_SELL_MARGIN = 18 
    OPERATION_TYPE_BROKER_FEE = 19 
    OPERATION_TYPE_BUY_MARGIN = 20  
    OPERATION_TYPE_DIVIDEND = 21 
    OPERATION_TYPE_SELL = 22 
    OPERATION_TYPE_COUPON = 23 
    OPERATION_TYPE_SUCCESS_FEE = 24 
    OPERATION_TYPE_DIVIDEND_TRANSFER = 25  
    OPERATION_TYPE_ACCRUING_VARMARGIN = 26 
    OPERATION_TYPE_WRITING_OFF_VARMARGIN = 27 
    OPERATION_TYPE_DELIVERY_BUY = 28 
    OPERATION_TYPE_DELIVERY_SELL = 29  
    OPERATION_TYPE_TRACK_MFEE = 30  
    OPERATION_TYPE_TRACK_PFEE = 31  
    OPERATION_TYPE_TAX_PROGRESSIVE = 32 
    OPERATION_TYPE_BOND_TAX_PROGRESSIVE = 33  
    OPERATION_TYPE_DIVIDEND_TAX_PROGRESSIVE = 34  
    OPERATION_TYPE_BENEFIT_TAX_PROGRESSIVE = 35 
    OPERATION_TYPE_TAX_CORRECTION_PROGRESSIVE = 36  
    OPERATION_TYPE_TAX_REPO_PROGRESSIVE = 37 
    OPERATION_TYPE_TAX_REPO = 38  
    OPERATION_TYPE_TAX_REPO_HOLD = 39 
    OPERATION_TYPE_TAX_REPO_REFUND = 40 
    OPERATION_TYPE_TAX_REPO_HOLD_PROGRESSIVE = 41 
    OPERATION_TYPE_TAX_REPO_REFUND_PROGRESSIVE = 42 
    OPERATION_TYPE_DIV_EXT = 43  
    OPERATION_TYPE_TAX_CORRECTION_COUPON = 44


class StopOrderDirection(str, Enum):
    STOP_ORDER_DIRECTION_UNSPECIFIED = 0
    STOP_ORDER_DIRECTION_BUY = 1
    STOP_ORDER_DIRECTION_SELL = 2


class StopOrderExpirationType(str, Enum):
    STOP_ORDER_EXPIRATION_TYPE_UNSPECIFIED = 0
    STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_CANCEL = 1
    STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_DATE = 2


class StopOrderType(str, Enum):
    STOP_ORDER_TYPE_UNSPECIFIED = 0
    STOP_ORDER_TYPE_TAKE_PROFIT = 1
    STOP_ORDER_TYPE_STOP_LOSS = 2
    STOP_ORDER_TYPE_STOP_LIMIT = 3






